# Generated by Django 4.0 on 2021-12-16 15:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total Price of the order', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Product Ordered Quantity', max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total Price (Ordered Quantity * Product Price)', max_digits=8)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='products',
            field=models.ManyToManyField(through='smartapp.BillItem', to='smartapp.Product'),
        ),
    ]
