# Generated by Django 4.0 on 2021-12-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_bill_billitem_bill_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Total Price (Ordered Quantity * Product Price)', max_digits=8),
        ),
    ]
